services:
  nginx:
    restart: always

  backend:
    restart: always
    environment:
      - NODE_ENV=production

  db:
    restart: always
    volumes:
      - haufe_postgres_data:/var/lib/postgresql/data
      - ./database/schema.sql:/docker-entrypoint-initdb.d/01-schema.sql

volumes:
  haufe_postgres_data: